Project sevenpreneur {
  database_type: 'PostgreSQL'
  note: 'Database for Sevenpreneur'
}

//////////////////
// Enumerations //
//////////////////

enum status_enum {
  active
  inactive
}

enum learning_method_enum {
  online
  onsite
  hybrid
}

enum category_enum {
  cohort
  playlist
  ai
  event
}

// Enumeration for the transactions table (t_*)

enum t_status_enum {
  pending
  paid
  failed
}

// Enumeration for the ai_chats table (c_*)

enum c_role_enum {
  user
  assistant
}

// Enumeration for the users table

enum occupation_enum {
  employee
  entrepreneur
  student
  freelance
  military
  unemployed
}

enum revenue_enum {
  below_50m
  between_50m_100m
  between_100m_500m
  between_500m_1b
  between_1b_10b
  between_10b_25b
  above_25b
}

enum num_employee_enum {
  small
  medium
  large
  xlarge
  xxlarge
}

enum legal_entity_enum {
  cv
  pt
  pt_tbk
  persero
  firma
  koperasi
  yayasan
  ud
  non_legal_entity
}

// Enumeration for the articles table (a_*)

enum a_status_enum {
  draft
  published
  unpublished
}

// Enumeration for the wa_assets table (wa_asset_*)

enum wa_asset_type {
  audio
  audio_voice
  document
  image
  sticker
  sticker_anim
  video
}

// Enumeration for the wa_conversations table (wa_*)

enum wa_lead_status {
  cold
  warm
  hot
}

// Enumeration for the wa_chats table (wac_*)

enum wac_direction {
  inbound
  outbound
}

enum wac_sender_type {
  user
  admin
}

enum wac_type {
  audio
  button
  contacts
  document
  edit
  image
  interactive
  location
  order
  reaction
  revoke
  sticker
  system
  text
  unsupported
  video
}

enum wac_status {
  sent
  delivered
  read
  failed
}

////////////
// Tables //
////////////

// Lookup tables

Table roles {
  id          smallint     [primary key]
  name        varchar      [note: 'unique, e.g. Administrator']
  permission  smallint
  created_at  timestamptz
  updated_at  timestamptz
}

Table industries {
  id             smallint     [primary key]
  industry_name  varchar      [note: 'unique, e.g. Information Technology']
  created_at     timestamptz
}

Table phone_country_codes {
  id            smallint  [primary key]
  country_name  varchar
  phone_code    varchar   [note: 'unique']
  emoji         varchar
}

Table payment_channels {
  id            smallint      [primary key]
  label         varchar
  code          varchar       [note: 'unique']
  method        varchar       [note: 'e.g. virtual account, e-wallet, QR, etc.']
  image         varchar
  status        status_enum   [note: 'default active']
  calc_percent  decimal(6,4)
  calc_flat     decimal(5,0)
  calc_vat      boolean
}

// User data

Table users {
  id                     uuid               [primary key]
  full_name              varchar            [note: 'e.g. Budi Sadikin']
  email                  varchar            [note: 'unique, e.g. budisadikin@gmail.com']
  phone_country_id       smallint           [ref: > phone_country_codes.id]
  phone_number           varchar
  avatar                 varchar
  role_id                smallint           [ref: > roles.id, note: 'default 3 (General User)']
  status                 status_enum        [note: 'default active']
  date_of_birth          date
  business_name          varchar
  industry_id            smallint           [ref: > industries.id]
  business_description   text
  occupation             occupation_enum
  yearly_revenue         revenue_enum
  total_employees        num_employee_enum
  company_profile_url    varchar
  business_age_years     integer
  legal_entity_type      legal_entity_enum
  average_selling_price  decimal(12,2)
  created_at             timestamptz
  updated_at             timestamptz
  last_login             timestamptz
  deleted_at             timestamptz
}

Table tokens {
  id          integer      [primary key]
  user_id     uuid         [ref: > users.id]
  is_active   boolean
  token       text         [note: 'unique']
  created_at  timestamptz
}

// LMS-related

Table cohorts {
  id            integer      [primary key]
  name          varchar
  description   varchar
  image         varchar
  image_banner  varchar
  image_square  varchar
  status        status_enum
  slug_url      varchar      [note: 'unique']
  start_date    timestamptz
  end_date      timestamptz
  published_at  timestamptz
  updated_at    timestamptz
  context       text
  tags          varchar
  deleted_at    timestamptz
  deleted_by    uuid         [ref: > users.id]
}

Table cohort_prices {
  id          integer        [primary key]
  cohort_id   integer        [ref: > cohorts.id]
  name        varchar
  amount      decimal(12,2)
  status      status_enum
  created_at  timestamptz
}

Table modules {
  id            integer      [primary key]
  cohort_id     integer      [ref: > cohorts.id]
  name          varchar
  description   varchar
  document_url  varchar
  status        status_enum
  created_at    timestamptz
  updated_at    timestamptz
}

Table learnings {
  id                 integer               [primary key]
  cohort_id          integer               [ref: > cohorts.id]
  name               varchar
  description        varchar
  method             learning_method_enum
  meeting_date       timestamptz
  meeting_url        varchar
  location_name      varchar
  location_url       varchar
  speaker_id         uuid                  [ref: > users.id]
  recording_url      varchar
  external_video_id  varchar
  price_id           integer               [ref: > cohort_prices.id]
  status             status_enum
  check_in           boolean               [note: 'default false']
  check_out          boolean               [note: 'default false']
  check_out_code     varchar
  feedback_form      varchar
  created_at         timestamptz
  updated_at         timestamptz
}

Table materials {
  id            integer      [primary key]
  learning_id   integer      [ref: > learnings.id]
  name          varchar
  description   varchar
  document_url  varchar
  status        status_enum
  created_at    timestamptz
  updated_at    timestamptz
}

Table discussion_starters {
  id           integer      [primary key]
  user_id      uuid         [ref: > users.id]
  learning_id  integer      [ref: > learnings.id]
  message      text
  created_at   timestamptz
  updated_at   timestamptz
}

Table discussion_replies {
  id          integer      [primary key]
  user_id     uuid         [ref: > users.id]
  starter_id  integer      [ref: > discussion_starters.id]
  message     text
  created_at  timestamptz
  updated_at  timestamptz
}

Table projects {
  id            integer      [primary key]
  cohort_id     integer      [ref: > cohorts.id]
  name          varchar
  description   varchar
  document_url  varchar
  deadline_at   timestamptz
  status        status_enum
  created_at    timestamptz
  updated_at    timestamptz
}

Table submissions {
  id            integer      [primary key]
  project_id    integer      [ref: > projects.id]
  submitter_id  uuid         [ref: > users.id]
  document_url  varchar
  comment       text
  is_favorite   boolean      [note: 'default false']
  created_at    timestamptz
  updated_at    timestamptz
}

Table attendances {
  learning_id  integer      [ref: > learnings.id]
  user_id      uuid         [ref: > users.id]
  check_in_at  timestamptz
  check_out_at timestamptz
}

// Playlist-related

Table playlists {
  id                 integer        [primary key]
  name               varchar
  tagline            varchar
  description        text
  video_preview_url  varchar
  image_url          varchar
  image_banner_url   varchar
  image_square_url   varchar
  price              decimal(12,2)
  status             status_enum
  slug_url           varchar
  published_at       timestamptz
  updated_at         timestamptz
  context            text
  tags               varchar
  deleted_at         timestamptz
  deleted_by         uuid           [ref: > users.id]
}

Table videos {
  id                 integer      [primary key]
  playlist_id        integer      [ref: > playlists.id]
  name               varchar
  description        text
  duration           integer
  image_url          varchar
  video_url          varchar
  num_order          smallint     [note: 'default 0']
  external_video_id  varchar
  status             status_enum
}

// Event-related

Table events {
  id             integer               [primary key, ref: <> users.id]
  name           varchar
  description    varchar
  image          varchar
  status         status_enum
  slug_url       varchar               [note: 'unique']
  start_date     timestamptz
  end_date       timestamptz
  method         learning_method_enum  [note: 'default onsite']
  meeting_url    varchar
  location_name  varchar
  location_url   varchar
  published_at   timestamptz
  updated_at     timestamptz
  context        text
  tags           varchar
  deleted_at     timestamptz
  deleted_by     uuid                  [ref: > users.id]
}

Table event_prices {
  id          integer        [primary key]
  event_id    integer        [ref: > events.id]
  name        varchar
  amount      decimal(12,2)
  status      status_enum
  created_at  timestamptz
}

// Template-related

Table templates {
  id            integer      [primary key]
  name          varchar
  description   varchar
  image         varchar
  document_url  varchar
  status        status_enum
  tags          varchar      [note: 'comma-separated list']
  created_at    timestamptz
  updated_at    timestamptz
}

// AI-tool-related

Table ai_tools {
  id           smallint     [primary key]
  name         varchar
  description  varchar
  slug_url     varchar
  status       status_enum
}

Table ai_results {
  id          char(21)     [primary key, note: 'default nanoid()']
  user_id     uuid         [ref: > users.id]
  ai_tool_id  smallint     [ref: > ai_tools.id]
  name        varchar
  result      json
  is_done     boolean      [note: 'default false']
  qstash_id   varchar
  created_at  timestamptz
}

// AI-chat-related

Table ai_conversations {
  id          char(21)     [primary key, note: 'default nanoid()']
  user_id     uuid         [ref: > users.id]
  name        varchar
  is_done     boolean      [note: 'default true']
  created_at  timestamptz
}

Table ai_chats {
  id          char(21)     [primary key, note: 'default nanoid()']
  conv_id     char(21)     [ref: > ai_conversations.id]
  role        c_role_enum
  message     text
  created_at  timestamptz
}

// Transaction-related

/**
 * The item_id column refers to
 * - cohort_prices.id if the category is cohort,
 * - playlists.id     if the category is playlist, or
 * - event_prices.id  if the category is event.
 */

Table discounts {
  id            integer        [primary key]
  name          varchar
  description   text
  code          varchar
  category      category_enum
  item_id       integer        [note: 'items ID based on category']
  calc_percent  decimal(7,4)
  status        status_enum
  start_date    timestamptz
  end_date      timestamptz
  created_at    timestamptz
  updated_at    timestamptz
}

Table transactions {
  id               char(21)       [primary key, note: 'default nanoid()']
  user_id          uuid           [ref: > users.id]
  category         category_enum
  item_id          integer        [note: 'items ID based on category']
  amount           decimal(12,2)
  discount_id      integer        [ref: > discounts.id]
  discount_amount  decimal(12,2)  [note: 'default 0']
  admin_fee        decimal(12,2)
  vat              decimal(12,2)
  currency         varchar        [note: 'IDR']
  invoice_number   varchar
  status           t_status_enum
  payment_method   varchar        [note: 'e.g. virtual account, e-wallet, QR, etc.']
  payment_channel  varchar        [note: 'details of payment method']
  paid_at          timestamptz
  created_at       timestamptz
  updated_at       timestamptz
}

// Tickers

Table ads_ticker {
  id          integer      [primary key, note: 'default 1']
  title       varchar
  callout     varchar
  target_url  varchar
  status      status_enum
  start_date  timestamptz
  end_date    timestamptz
  updated_at  timestamptz
}

// Article-related

Table article_categories {
  id          smallint     [primary key]
  name        varchar
  status      status_enum
  slug        varchar
  created_at  timestamptz
}

Table articles {
  id            integer        [primary key, note: 'starts at 77777']
  title         varchar
  insight       varchar
  image_url     varchar
  body_content  json
  status        a_status_enum
  category_id   smallint       [ref: > article_categories.id]
  keywords      varchar
  author_id     uuid           [ref: > users.id]
  reviewer_id   uuid           [ref: > users.id]
  slug_url      varchar
  published_at  timestamptz
  updated_at    timestamptz
}

// Interstitial Ads

Table ads_interstitial {
  id              integer      [primary key, note: 'default 1']
  title           varchar
  call_to_action  varchar
  target_url      varchar
  image_desktop   varchar
  image_mobile    varchar
  status          status_enum
  start_date      timestamptz
  end_date        timestamptz
  updated_at      timestamptz
}

// WhatsApp-chat-related

Table wa_conversations {
  id            char(21)        [primary key, note: 'default nanoid()']
  user_id       uuid            [ref: > users.id]
  full_name     varchar
  phone_number  varchar
  handler_id    uuid            [ref: > users.id]
  lead_status   wa_lead_status  [note: 'default cold']
  winning_rate  smallint        [note: 'default 0']
  note          varchar
  last_read_id  char(21)        [ref: > wa_chats.id]
  created_at    timestamptz
  updated_at    timestamptz
}

Table wa_chats {
  id            char(21)         [primary key, note: 'default nanoid()']
  conv_id       char(21)         [ref: > wa_conversations.id]
  wam_id        varchar
  direction     wac_direction
  sender_type   wac_sender_type
  reply_to_id   char(21)         [ref: > wa_chats.id]
  type          wac_type
  message       varchar
  attachment    json
  status        wac_status
  sent_at       timestamptz
  delivered_at  timestamptz
  read_at       timestamptz
  failed_at     timestamptz
  created_at    timestamptz
  updated_at    timestamptz
}

Table wa_assets {
  id           serial          [primary key]
  url          varchar         [not null]
  type         wa_asset_type   [not null]
  description  varchar
  created_at   timestamptz
  updated_at   timestamptz
}

// Relation Tables //

Table users_cohorts {
  user_id          uuid     [ref: > users.id]
  cohort_id        integer  [ref: > cohorts.id]
  cohort_price_id  integer  [ref: > cohort_prices.id]
  certificate_url  varchar
  is_scout         boolean  [note: 'default false']
}

Table users_playlists {
  user_id      uuid     [ref: > users.id]
  playlist_id  integer  [ref: > playlists.id]
  rating       integer
  review       varchar
}

Table educators_playlists {
  user_id      uuid     [ref: > users.id]
  playlist_id  integer  [ref: > playlists.id]
}

Table users_events {
  user_id   uuid     [ref: > users.id]
  event_id  integer  [ref: > events.id]
}

Table users_templates {
  user_id  uuid  [ref: > users.id]
}

Table users_ai_tools {
  user_id  uuid  [ref: > users.id]
}
